### ISSUE TITLE
StopIteration error on some inputs

### ISSUE THREAD

**Issue by sumnerevans** [jackrosenthal/csmdirsearch#1]
Sometimes (but not always) I get a StopIteration error when querying a name.

```
$ dirsearch 'evans'
Ryan Bevans
Faculty, Mining Engineering
Major: Mining Engineering
Work Telephone: (303)273-3700
Business Email: rbevans@mymail.mines.edu

Traceback (most recent call last):
  File "/home/sumner/.local/lib/python3.7/site-packages/csmdirsearch/dirsearch.py", line 220, in search_by_name
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sumner/.local/bin/dirsearch", line 11, in <module>
    load_entry_point('csmdirsearch==0.1.0', 'console_scripts', 'dirsearch')()
  File "/home/sumner/.local/lib/python3.7/site-packages/csmdirsearch/__main__.py", line 48, in main
    fmt(func(args.query))
  File "/home/sumner/.local/lib/python3.7/site-packages/csmdirsearch/__main__.py", line 24, in format_pretty
    for result in results:
  File "/home/sumner/.local/lib/python3.7/site-packages/csmdirsearch/dirsearch.py", line 266, in search
    for result in search_by_partial(query, executor=executor):
  File "/home/sumner/.local/lib/python3.7/site-packages/csmdirsearch/dirsearch.py", line 255, in search_by_partial
    rs = future.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
RuntimeError: generator raised StopIteration
```

**Comment by jackrosenthal** [comment]
Should be fixed in ``master``. I will clean up some other stuff and make a new release on PyPI soon.
