### ISSUE TITLE
PyPi Installation issue

### ISSUE THREAD

**Issue by Warfields** [jackrosenthal/csmdirsearch#3]
This is a bit of a weird one, installing from source is fine. Installation from PyPi yields the following. Also willing to look at #2 

```
$ dirsearch z

Brian Etz
Graduate Student, Chemistry
Major: Applied Chemistry
Business Email: etz@mymail.mines.edu

Desheng Zhu
Faculty, Civil and Environmental Engineering
Work Telephone: (303)273-3669
Business Email: 

Zhipeng Qi
Faculty, Geophysics
Business Email: 

Zhenzhen Yu
Faculty, Metallurgical and Materials Engineering
Work Telephone: (303)273-3798
Business Email: zyu@mines.edu

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/csmdirsearch/dirsearch.py", line 220, in search_by_name
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/dirsearch", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/csmdirsearch/__main__.py", line 48, in main
    fmt(func(args.query))
  File "/usr/local/lib/python3.7/site-packages/csmdirsearch/__main__.py", line 24, in format_pretty
    for result in results:
  File "/usr/local/lib/python3.7/site-packages/csmdirsearch/dirsearch.py", line 266, in search
    for result in search_by_partial(query, executor=executor):
  File "/usr/local/lib/python3.7/site-packages/csmdirsearch/dirsearch.py", line 255, in search_by_partial
    rs = future.result()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
RuntimeError: generator raised StopIteration
```

**Comment by Warfields** [comment]
Yeah, your last commit never made it to PyPi

**Comment by jackrosenthal** [comment]
If you plan on maintaining this, can you update the release on PyPI when you are at that? We can look at transferring owner of the package on there.

**Comment by Warfields** [comment]
Sounds good

**Comment by Warfields** [comment]
> If you plan on maintaining this, can you update the release on PyPI when you are at that?

Yes
